# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
  
jobs:
  test:
    docker:
      - image: 'cimg/node:13.12-browser'
    steps:
      - browser-tools/install-browser-tools
workflows: null
